"""Initializate role for user

Revision ID: 856319e61d13
Revises: 70b57ce35ca2
Create Date: 2025-08-09 17:23:01.942801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856319e61d13'
down_revision: Union[str, Sequence[str], None] = '70b57ce35ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
user_role_enum = sa.Enum('ADMIN', 'USER', name='user_role')

def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
