"""ProjectParticipant model

Revision ID: cf2e2c142a7c
Revises: 856319e61d13
Create Date: 2025-08-27 21:58:52.469215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app 
import app.core
import app.core.database


# revision identifiers, used by Alembic.
revision: str = 'cf2e2c142a7c'
down_revision: Union[str, Sequence[str], None] = '856319e61d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_participants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_participants_projects_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_project_participants_users_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_project_participants_project_id'), 'project_participants', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_participants_user_id'), 'project_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_participants_user_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_project_id'), table_name='project_participants')
    op.drop_table('project_participants')
    # ### end Alembic commands ###
